FROM node:20-alpine AS base
WORKDIR /app

RUN apk add --no-cache libc6-compat
COPY package.json package-lock.json ./
# RUN npm install -D @swc/cli @swc/core
RUN npm i
COPY . .
USER nextjs

EXPOSE 3000

CMD ["npm", "run", "dev"]


FROM base AS runner
WORKDIR /app
ENV NODE_ENV=development

RUN if ! id "nextjs" &>/dev/null; then \
  addgroup --system --gid 1002 nodejs && \
  adduser --system --ingroup nodejs nextjs; \
  fi

COPY --from=deps /app/node_modules ./node_modules
COPY ./public /app/public
COPY . .

RUN chown -R nextjs:nodejs /app