import type { Metadata } from "next";
import localFont from "next/font/local";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import { Layout } from "antd";
import { Content } from "antd/es/layout/layout";

 const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
 const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AntdRegistry>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Layout
          style={{
            minHeight: 'calc(100vh - 3.5rem - 24px)',
            padding: "12px",
            gap: "12px",
            background: '#fff'
          }}
        >
          <Content>{children}</Content>
        </Layout>
        </body>
      </AntdRegistry>
    </html>
  );
}
